// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonical/jimm/v3/internal/jimm/juju (interfaces: GitHubClient)
//
// Generated by this command:
//
//	mockgen -package mocks -typed -destination ./mocks/github_mock.go github.com/canonical/jimm/v3/internal/jimm/juju GitHubClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	github "github.com/google/go-github/v69/github"
	gomock "go.uber.org/mock/gomock"
)

// MockGitHubClient is a mock of GitHubClient interface.
type MockGitHubClient struct {
	ctrl     *gomock.Controller
	recorder *MockGitHubClientMockRecorder
	isgomock struct{}
}

// MockGitHubClientMockRecorder is the mock recorder for MockGitHubClient.
type MockGitHubClientMockRecorder struct {
	mock *MockGitHubClient
}

// NewMockGitHubClient creates a new mock instance.
func NewMockGitHubClient(ctrl *gomock.Controller) *MockGitHubClient {
	mock := &MockGitHubClient{ctrl: ctrl}
	mock.recorder = &MockGitHubClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitHubClient) EXPECT() *MockGitHubClientMockRecorder {
	return m.recorder
}

// ListReleases mocks base method.
func (m *MockGitHubClient) ListReleases(ctx context.Context, owner, repo string, opts *github.ListOptions) ([]*github.RepositoryRelease, *github.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReleases", ctx, owner, repo, opts)
	ret0, _ := ret[0].([]*github.RepositoryRelease)
	ret1, _ := ret[1].(*github.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListReleases indicates an expected call of ListReleases.
func (mr *MockGitHubClientMockRecorder) ListReleases(ctx, owner, repo, opts any) *MockGitHubClientListReleasesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReleases", reflect.TypeOf((*MockGitHubClient)(nil).ListReleases), ctx, owner, repo, opts)
	return &MockGitHubClientListReleasesCall{Call: call}
}

// MockGitHubClientListReleasesCall wrap *gomock.Call
type MockGitHubClientListReleasesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGitHubClientListReleasesCall) Return(arg0 []*github.RepositoryRelease, arg1 *github.Response, arg2 error) *MockGitHubClientListReleasesCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGitHubClientListReleasesCall) Do(f func(context.Context, string, string, *github.ListOptions) ([]*github.RepositoryRelease, *github.Response, error)) *MockGitHubClientListReleasesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGitHubClientListReleasesCall) DoAndReturn(f func(context.Context, string, string, *github.ListOptions) ([]*github.RepositoryRelease, *github.Response, error)) *MockGitHubClientListReleasesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
